Fix NoSuchMethodError String.stripIndent with Java 11
The method String.stripIndent() requires Java 15 or later.

This patch uses instead String.stripIndent(true) which is
implemented by the groovy runtime and allows backward compatibility
with Java 11 and later

Signed-off-by: Paolo Di Tommaso <paolo.ditommaso@gmail.com>